### ISSUE TITLE
Unexpected Identifier error

### ISSUE THREAD

**Issue by sprguillen** [david-szabo97/Infusionsoft-Node-SDK#1]
Hi, can you please provide some instructions on how to use the SDK? I have the following error:

 C:\Users\sprgu\Workspace\freelance\infusionsoft-auth\node_modules\infusionsoft-node-sdk\lib\oauth2\index.js:66
  async requestAccessToken (code) {
        ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sprgu\Workspace\freelance\infusionsoft-auth\node_modules\infusionsoft-node-sdk\index.js:1:84)

Here is how I called this on my node app:

const express = require('express')
const app = express()
const http = require('http')
const ins = require('infusionsoft-node-sdk')
const conf = require('./config.js')

app.get('/reauth', function (req, res) {
	let infusionsoftConf = conf.get('infusionsoft')
	let infusionSoft = new ins.OAuth2(infusionsoftConf)
})

app.listen(3000, () => console.log('Successfully listened to app 3000'))

Please help me!

**Comment by david-szabo97** [comment]
The SDK is not ready for production. I have a private version which I use internally for my projects.
This is an unofficial SDK, I have never released the latest version to the public. The only version which is released is v0.0.1. Which is like a pre-alpha WIP version.

OAuth2 API connection was never tested. I have only used the Legacy connection.

Anyway, seems like you are using an old Node.js version. async class methods available in Node.js v8.x. Upgrading your Node.js might fix this issue, but as I said, the SDK is not ready for production.

**Comment by sprguillen** [comment]
Thanks mate.. Noted..
