### ISSUE TITLE
Question -- for an application is privateKey ...

### ISSUE THREAD

**Issue by horatio-sans-serif** [david-szabo97/Infusionsoft-Node-SDK#2]
Question -- for an application is privateKey the API key as specified in the InfusionSoft developer portal for the application?  Or is it the authorizing user's "encrypted key" from their InfusionSoft user account?

The Infusionsoft documentation is insanely frustrating. Thanks!

**Comment by david-szabo97** [comment]
@fictorial This SDK is unofficial and still very WIP.

I guess you mean the Legacy API - there you should use the encrypted key from the IS user account.

**Comment by horatio-sans-serif** [comment]
I determined that if I use the refreshed access token method, I don’t need to specify a value for privateKey (API key) in the XMLRPC API. Unfortunately some features aren’t exposed to the REST API so I have to use both. Wacky system.
